---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: b1bb04d292c7a7844aebe995ffb83625e5c9244b
    dapr.io/enable-api-logging: "true"
    dapr.io/enabled: "true"
    dapr.io/app-id: springbootapp
  labels:
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/name: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: "1.0"
      app.kubernetes.io/name: order-service
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: b1bb04d292c7a7844aebe995ffb83625e5c9244b
        dapr.io/enable-api-logging: "true"
        dapr.io/enabled: "true"
        dapr.io/app-id: springbootapp
      labels:
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/name: order-service
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: localhost:5000/cmoulliard/order-service:1.0
          imagePullPolicy: IfNotPresent
          name: order-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: b1bb04d292c7a7844aebe995ffb83625e5c9244b
    dapr.io/enable-api-logging: "true"
    dapr.io/enabled: "true"
    dapr.io/app-id: springbootapp
  labels:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/version: "1.0"
  name: order-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: order-service
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
