---
project:
  root: file:///Users/cmoullia/code/dapr/my-dapr/demo/java/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: order-service
    version: "1.0"
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.8.7
    outputFile: file:///Users/cmoullia/code/dapr/my-dapr/demo/java/target/order-service-1.0.jar
    classOutputDir: file:///Users/cmoullia/code/dapr/my-dapr/demo/java/target/classes/
    resourceDir: file:///Users/cmoullia/code/dapr/my-dapr/demo/java/target/classes/
  scmInfo:
    root: file:///Users/cmoullia/code/dapr/my-dapr/
    branch: main
    commit: b1bb04d292c7a7844aebe995ffb83625e5c9244b
    remote:
      '[remote "origin"]': https://github.com/dapr/dapr.git
partOf: null
name: order-service
version: "1.0"
deploymentKind: Deployment
annotations:
  - key: dapr.io/enabled
    value: "true"
  - key: dapr.io/app-id
    value: springbootapp
  - key: dapr.io/enable-api-logging
    value: "true"
  - key: dapr.io/enabled
    value: "true"
  - key: dapr.io/app-id
    value: springbootapp
  - key: dapr.io/enable-api-logging
    value: "true"
  - key: dapr.io/enabled
    value: "true"
  - key: dapr.io/app-id
    value: springbootapp
  - key: dapr.io/enable-api-logging
    value: "true"
workingDir: null
serviceAccount: null
ports:
  - name: http
    containerPort: 8080
    hostPort: 80
    nodePort: null
    path: /
    protocol: null
  - name: null
    containerPort: 8080
    hostPort: 80
    nodePort: 0
    path: /
    protocol: TCP
serviceType: ClusterIP
imagePullPolicy: IfNotPresent
livenessProbe:
  httpActionPath: ""
  execAction: ""
  tcpSocketAction: ""
  grpcAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpActionPath: ""
  execAction: ""
  tcpSocketAction: ""
  grpcAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
startupProbe:
  httpActionPath: ""
  execAction: ""
  tcpSocketAction: ""
  grpcAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
requestResources:
  memory: ""
  cpu: ""
limitResources:
  memory: ""
  cpu: ""
autoDeployEnabled: false
replicas: 1
deploymentStrategy: None
rollingUpdate:
  maxUnavailable: 25%
  maxSurge: 25%
ingress:
  host: ""
  ingressClassName: ""
  targetPort: http
  expose: false
  tlsSecretName: ""
headless: false
